version: "3.8"
services:
  ui:
    build: ./ui
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://scraper:8000
    depends_on:
      - scraper

  scraper:
    build: ./scraper
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1